server:
  port: 8899
spring:
  application:
    name: Order Management Application
  datasource:
    url: jdbc:mysql://localhost:3306/order_management
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true



